// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chats.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateChat(ctx context.Context, name string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, name)
	var i Chat
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getChat = `-- name: GetChat :one
SELECT id, name FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id int32) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT id, name FROM chats
ORDER BY id
`

func (q *Queries) ListChats(ctx context.Context) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
