// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, sender_id, content, sent_at
`

type CreateMessageParams struct {
	ChatID   sql.NullInt64 `json:"chat_id"`
	SenderID sql.NullInt32 `json:"sender_id"`
	Content  string        `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT id, chat_id, sender_id, content, sent_at FROM messages
WHERE chat_id = $1
ORDER BY sent_at DESC
LIMIT $2 OFFSET $3
`

type ListMessagesByChatParams struct {
	ChatID sql.NullInt64 `json:"chat_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChat, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
