// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Chat struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Message struct {
	ID       int32         `json:"id"`
	ChatID   sql.NullInt64 `json:"chat_id"`
	SenderID sql.NullInt32 `json:"sender_id"`
	Content  string        `json:"content"`
	SentAt   sql.NullTime  `json:"sent_at"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
