// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateChat(ctx context.Context, name string) (Chat, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, name string) (User, error)
	GetChat(ctx context.Context, id int32) (Chat, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListChats(ctx context.Context) ([]Chat, error)
	ListMessagesByChat(ctx context.Context, arg ListMessagesByChatParams) ([]Message, error)
	ListUsers(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
